spring:
  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true

server:
  port: 31000
  servlet:
    encoding:
      charset: UTF-8

loa:
  apiKey: #발급받은API키#
  apiUrl: https://developer-lostark.game.onstove.com
---
spring:
  config:
    activate:
      on-profile: "local"

  log:
    file-path: D:\logs\loa\loa.log


---
spring:
  config:
    activate:
      on-profile: "prod"

  log:
    file-path: /dudqls3kr/logs/loa/loa.log
